services:
    _defaults:
          # automatically injects dependencies in your services
          autowire: true
          # automatically registers your services as commands, event subscribers, etc.
          autoconfigure: true
          public: false


    FrontBundle\:
          resource: '../../../src/FrontBundle/*'


    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    FrontBundle\Controller\:
        resource: '../../../src/FrontBundle/Controller'
        public: true
        tags: ['controller.service_arguments']


    FrontBundle\Imagine\PartImageLoader:
        tags:
            - { name: liip_imagine.binary.loader, loader: part_image_loader }

    FrontBundle\Imagine\SetImageLoader:
        tags:
            - { name: liip_imagine.binary.loader, loader: set_image_loader }


    # KNP Menu

    menu.builder.main:
        class: FrontBundle\Menu\Builder
        arguments: ['@knp_menu.factory', '@request_stack']
        public: true
        tags:
          - { name: knp_menu.menu_builder, method: mainMenu, alias: mainMenu }

    Knp\Menu\FactoryInterface:
        alias: knp_menu.factory


    # Twig

    FrontBundle\Twig\AppExtension:
        arguments:
            $webDir: "%kernel.root_dir%/../web"
        tags:
            - { name: twig.extension }
