services:
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        public: false


    LoaderBundle\:
        resource: '../../../src/LoaderBundle/*'
        exclude: '../../../src/LoaderBundle/{Exception}'

    LoaderBundle\Service\Stl\StlRendererService:
        arguments:
            $layout: '%kernel.root_dir%/Resources/povray_layout/layout.tmpl'
            $povray: '%povray_bin%'
            $stl2pov: '%stl2pov_bin%'

    LoaderBundle\Service\Stl\StlConverterService:
        arguments:
            $ldview: '%ldview_bin%'

    LoaderBundle\Service\Stl\StlFixerService:
        arguments:
            $ADMesh: '%admesh_bin%'


    LoaderBundle\Service\BaseLoader:
        abstract:  true

    LoaderBundle\Service\ModelLoader:
        arguments:
            $logger: '@monolog.logger.loader'

    LoaderBundle\Service\RebrickableLoader:
        arguments:
            $rebrickableDownloadUrl: '%app.rebrickable_downloads_url%'
            $logger: '@monolog.logger.loader'

    LoaderBundle\Service\ImageLoader:
        arguments:
            $rebrickableDownloadUrl: '%app.rebrickable_downloads_url%'
            $logger: '@monolog.logger.loader'

    LoaderBundle\Util\RelationMapper:
        arguments:
            - '@app.relations.cache_provider'
        calls:
            - [ loadResource, ['%kernel.root_dir%/Resources/relations/part_model.yml', 'part_model']]
            - [ loadResource, ['%kernel.root_dir%/Resources/relations/alias_model.yml', 'alias_model']]
